package main

var memberTemplate = "\t%v\t%v\t`db:\"%v\" bson:\"%v\" comment:\"%v\" json:\"%v\" xml:\"%v\"`"
var replaces = &map[string]string{
	"packageName":   "",
	"imports":       "",
	"structName":    "",
	"structComment": "",
	"attributes":    "",
	"reset":         "",
	"asMap":         "",
	"asRow":         "",
	"fromRowCase":   "",
	"setCase":       "",
	"tableName":     "",
	"beforeInsert":  "",
	"afterInsert":   "",
	"beforeUpdate":  "",
	"setUpdatedAt":  "",
	"beforeDelete":  "",
}
var structFuncs = map[string]string{
	`Trans`:         `Trans`,
	`Use`:           `Use`,
	`Objects`:       `Objects`,
	`NewObjects`:    `NewObjects`,
	`NewParam`:      `NewParam`,
	`SetParam`:      `SetParam`,
	`Get`:           `Get`,
	`List`:          `List`,
	`ListByOffset`:  `ListByOffset`,
	`Add`:           `Add`,
	`Edit`:          `Edit`,
	`Upsert`:        `Upsert`,
	`Delete`:        `Delete`,
	`Count`:         `Count`,
	`GroupBy`:       `GroupBy`,
	`KeyBy`:         `KeyBy`,
	`Setter`:        `Setter`,
	`SetField`:      `SetField`,
	`SetFields`:     `SetFields`,
	`Reset`:         `Reset`,
	`AsMap`:         `AsMap`,
	`AsRow`:         `AsRow`,
	`BatchValidate`: `BatchValidate`,
	`Validate`:      `Validate`,
}
var structTemplate = `// @generated Do not edit this file, which is automatically generated by the generator.

package {{packageName}}

import (
	"fmt"

	"github.com/webx-top/db"
	"github.com/webx-top/db/lib/factory"
	"github.com/webx-top/echo"
	"github.com/webx-top/echo/param"
	{{imports}}
)

type Slice_{{structName}} []*{{structName}}

func (s Slice_{{structName}}) Range(fn func(m factory.Model) error ) error {
	for _, v := range s {
		if err := fn(v); err != nil {
			return err
		}
	}
	return nil
}

func (s Slice_{{structName}}) RangeRaw(fn func(m *{{structName}}) error ) error {
	for _, v := range s {
		if err := fn(v); err != nil {
			return err
		}
	}
	return nil
}

// {{structName}} {{structComment}}
type {{structName}} struct {
	param   *factory.Param
	trans	*factory.Transaction
	objects []*{{structName}}
	namer   func(string) string
	connID  int
	context echo.Context
	
{{attributes}}
}

func (this *{{structName}}) Trans() *factory.Transaction {
	return this.trans
}

func (this *{{structName}}) Use(trans *factory.Transaction) factory.Model {
	this.trans = trans
	return this
}

func (this *{{structName}}) SetContext(ctx echo.Context) factory.Model {
	this.context = ctx
	return this
}

func (this *{{structName}}) Context() echo.Context {
	return this.context
}

func (this *{{structName}}) SetConnID(connID int) factory.Model {
	this.connID = connID
	return this
}

func (this *{{structName}}) New(structName string, connID ...int) factory.Model {
	if len(connID) > 0 {
		return factory.NewModel(structName,connID[0]).Use(this.trans)
	}
	return factory.NewModel(structName,this.connID).Use(this.trans)
}

func (this *{{structName}}) Objects() []*{{structName}} {
	if this.objects == nil {
		return nil
	}
	return this.objects[:]
}

func (this *{{structName}}) NewObjects() factory.Ranger {
	return &Slice_{{structName}}{}
}

func (this *{{structName}}) InitObjects() *[]*{{structName}} {
	this.objects = []*{{structName}}{}
	return &this.objects
}

func (this *{{structName}}) NewParam() *factory.Param {
	return factory.NewParam(factory.DefaultFactory).SetIndex(this.connID).SetTrans(this.trans).SetCollection(this.Name_()).SetModel(this)
}

func (this *{{structName}}) SetNamer(namer func (string) string) factory.Model {
	this.namer = namer
	return this
}

func (this *{{structName}}) Short_() string {
	return "{{tableName}}"
}

func (this *{{structName}}) Struct_() string {
	return "{{structName}}"
}

func (this *{{structName}}) Name_() string {
	if this.namer != nil {
		return WithPrefix(this.namer(this.Short_()))
	}
	return WithPrefix(factory.TableNamerGet(this.Short_())(this))
}

func (this *{{structName}}) Namer() func(string) string {
	return this.namer
}

func (this *{{structName}}) CPAFrom(source factory.Model) factory.Model {
	this.SetContext(source.Context())
	this.Use(source.Trans())
	this.SetNamer(source.Namer())
	return this
}

func (this *{{structName}}) SetParam(param *factory.Param) factory.Model {
	this.param = param
	return this
}

func (this *{{structName}}) Param() *factory.Param {
	if this.param == nil {
		return this.NewParam()
	}
	return this.param
}

func (this *{{structName}}) Get(mw func(db.Result) db.Result, args ...interface{}) error {
	return this.Param().SetArgs(args...).SetRecv(this).SetMiddleware(mw).One()
}

func (this *{{structName}}) List(recv interface{}, mw func(db.Result) db.Result, page, size int, args ...interface{}) (func() int64, error) {
	if recv == nil {
		recv = this.InitObjects()
	}
	return this.Param().SetArgs(args...).SetPage(page).SetSize(size).SetRecv(recv).SetMiddleware(mw).List()
}

func (this *{{structName}}) GroupBy(keyField string, inputRows ...[]*{{structName}}) map[string][]*{{structName}} {
	var rows []*{{structName}}
	if len(inputRows) > 0 {
		rows = inputRows[0]
	} else {
		rows = this.Objects()
	}
	r := map[string][]*{{structName}}{}
	for _, row := range rows {
		dmap := row.AsMap()
		vkey := fmt.Sprint(dmap[keyField])
		if _, y := r[vkey]; !y {
			r[vkey] = []*{{structName}}{}
		}
		r[vkey] = append(r[vkey], row)
	}
	return r
}

func (this *{{structName}}) KeyBy(keyField string, inputRows ...[]*{{structName}}) map[string]*{{structName}} {
	var rows []*{{structName}}
	if len(inputRows) > 0 {
		rows = inputRows[0]
	} else {
		rows = this.Objects()
	}
	r := map[string]*{{structName}}{}
	for _, row := range rows {
		dmap := row.AsMap()
		vkey := fmt.Sprint(dmap[keyField])
		r[vkey] = row
	}
	return r
}

func (this *{{structName}}) AsKV(keyField string, valueField string, inputRows ...[]*{{structName}}) map[string]interface{} {
	var rows []*{{structName}}
	if len(inputRows) > 0 {
		rows = inputRows[0]
	} else {
		rows = this.Objects()
	}
	r := map[string]interface{}{}
	for _, row := range rows {
		dmap := row.AsMap()
		vkey := fmt.Sprint(dmap[keyField])
		r[vkey] = dmap[valueField]
	}
	return r
}

func (this *{{structName}}) ListByOffset(recv interface{}, mw func(db.Result) db.Result, offset, size int, args ...interface{}) (func() int64, error) {
	if recv == nil {
		recv = this.InitObjects()
	}
	return this.Param().SetArgs(args...).SetOffset(offset).SetSize(size).SetRecv(recv).SetMiddleware(mw).List()
}

func (this *{{structName}}) Add() (pk interface{}, err error) {
	{{beforeInsert}}
	err = DBI.Fire("creating", this, nil)
	if err != nil {
		return
	}
	pk, err = this.Param().SetSend(this).Insert()
	{{afterInsert}}
	if err == nil {
		err = DBI.Fire("created", this, nil)
	}
	return
}

func (this *{{structName}}) Edit(mw func(db.Result) db.Result, args ...interface{}) (err error) {
	{{beforeUpdate}}
	if err = DBI.Fire("updating", this, mw, args...); err != nil {
		return
	}
	if err = this.Setter(mw, args...).SetSend(this).Update(); err != nil {
		return
	}
	return DBI.Fire("updated", this, mw, args...)
}

func (this *{{structName}}) Setter(mw func(db.Result) db.Result, args ...interface{}) *factory.Param {
	return this.Param().SetArgs(args...).SetMiddleware(mw)
}

func (this *{{structName}}) SetField(mw func(db.Result) db.Result, field string, value interface{}, args ...interface{}) (err error) {
	return this.SetFields(mw, map[string]interface{}{
		field: value,
	}, args...)
}

func (this *{{structName}}) SetFields(mw func(db.Result) db.Result, kvset map[string]interface{}, args ...interface{}) (err error) {
	{{setUpdatedAt}}
	m := *this
	m.FromRow(kvset)
	var editColumns []string
	for column := range kvset {
		editColumns = append(editColumns, column)
	}
	if err = DBI.FireUpdate("updating", &m, editColumns, mw, args...); err != nil {
		return
	}
	if err = this.Setter(mw, args...).SetSend(kvset).Update(); err != nil {
		return
	}
	return DBI.FireUpdate("updated", &m, editColumns, mw, args...)
}

func (this *{{structName}}) Upsert(mw func(db.Result) db.Result, args ...interface{}) (pk interface{}, err error) {
	pk, err = this.Param().SetArgs(args...).SetSend(this).SetMiddleware(mw).Upsert(func() error { {{beforeUpdate}}
		return DBI.Fire("updating", this, mw, args...)
	}, func() error { {{beforeInsert}}
		return DBI.Fire("creating", this, nil)
	})
	{{afterInsert}}
	if err == nil {
		if pk == nil {
			err = DBI.Fire("updated", this, mw, args...)
		} else {
			err = DBI.Fire("created", this, nil)
		}
	} 
	return 
}

func (this *{{structName}}) Delete(mw func(db.Result) db.Result, args ...interface{})  (err error) {
	{{beforeDelete}}
	if err = DBI.Fire("deleting", this, mw, args...); err != nil {
		return
	}
	if err = this.Param().SetArgs(args...).SetMiddleware(mw).Delete(); err != nil {
		return
	}
	return DBI.Fire("deleted", this, mw, args...)
}

func (this *{{structName}}) Count(mw func(db.Result) db.Result, args ...interface{}) (int64, error) {
	return this.Param().SetArgs(args...).SetMiddleware(mw).Count()
}

func (this *{{structName}}) Reset() *{{structName}} {
{{reset}}
	return this
}

func (this *{{structName}}) AsMap() map[string]interface{} {
	r := map[string]interface{}{}
{{asMap}}
	return r
}

func (this *{{structName}}) FromRow(row map[string]interface{}) {
	for key, value := range rows {
		switch key {
{{fromRowCase}}
		}
	}
}

func (this *{{structName}}) Set(key interface{}, value ...interface{}) {
	switch k := key.(type) {
		case map[string]interface{}:
			for kk, vv := range k {
				this.Set(kk, vv)
			}
		default:
			var (
				kk string
				vv interface{}
			)
			if k, y := key.(string); y {
				kk = k
			} else {
				kk = fmt.Sprint(key)
			}
			if len(value) > 0 {
				vv = value[0]
			}
			switch kk {
{{setCase}}
			}
	}
}

func (this *{{structName}}) AsRow() map[string]interface{} {
	r := map[string]interface{}{}
{{asRow}}
	return r
}

func (this *{{structName}}) BatchValidate(kvset map[string]interface{}) error {
	if kvset == nil {
		kvset = this.AsRow()
	}
	return factory.BatchValidate(this.Short_(), kvset)
}

func (this *{{structName}}) Validate(field string, value interface{}) error {
	return factory.Validate(this.Short_(), field, value)
}

`

var modelReplaces = &map[string]string{
	"packageName":       "",
	"imports":           "",
	"structName":        "",
	"schemaPackagePath": "",
	"schemaPackageName": "",
	"baseName":          "",
}
var modelBaseTemplate = `package {{packageName}}

import (
	"github.com/webx-top/echo"
	{{imports}}
)

type {{structName}} struct {
	echo.Context
}
`

var modelTemplate = `package {{packageName}}

import (
	"{{schemaPackagePath}}"
	"github.com/webx-top/echo"
	{{imports}}
)
				
func New{{structName}}(ctx echo.Context) *{{structName}} {
	return &{{structName}}{
		{{structName}}: &{{schemaPackageName}}.{{structName}}{},
		{{baseName}}:   &{{baseName}}{Context: ctx},
	}
}

type {{structName}} struct {
	*{{schemaPackageName}}.{{structName}}
	*{{baseName}}
}

`

var initFileTemplate = `// @generated Do not edit this file, which is automatically generated by the generator.

package {{packageName}}

import (
	"github.com/webx-top/db/lib/factory"
)

var WithPrefix = func(tableName string) string {
	return "{{prefix}}" + tableName
}

var DBI = factory.NewDBI()

func init(){
	{{initCode}}
}

`
