//Generated by webx-top/db
package dbschema

import (
	"github.com/webx-top/db"
	"github.com/webx-top/db/lib/factory"
	
	"time"
)

type Config struct {
	trans	*factory.Transaction
	
	Id     	uint    	`db:"id,omitempty,pk" bson:"id,omitempty" comment:"主键ID" json:"id" xml:"id"`
	Key    	string  	`db:"key" bson:"key" comment:"配置项" json:"key" xml:"key"`
	Val    	string  	`db:"val" bson:"val" comment:"配置值" json:"val" xml:"val"`
	Updated	uint    	`db:"updated" bson:"updated" comment:"更新时间" json:"updated" xml:"updated"`
}

func (this *Config) Trans() *factory.Transaction {
	return this.trans
}

func (this *Config) Use(trans *factory.Transaction) *Config {
	this.trans = trans
	return this
}

func (this *Config) Param() *factory.Param {
	return factory.NewParam(factory.DefaultFactory).SetTrans(this.trans).SetCollection("config")
}

func (this *Config) Get(mw func(db.Result) db.Result) error {
	return this.Param().SetRecv(this).SetMiddleware(mw).One()
}

func (this *Config) List(mw func(db.Result) db.Result, page, size int) ([]*Config, func() int64, error) {
	r := []*Config{}
	counter, err := this.Param().SetPage(page).SetSize(size).SetRecv(&r).SetMiddleware(mw).List()
	return r, counter, err
}

func (this *Config) ListByOffset(mw func(db.Result) db.Result, offset, size int) ([]*Config, func() int64, error) {
	r := []*Config{}
	counter, err := this.Param().SetOffset(offset).SetSize(size).SetRecv(&r).SetMiddleware(mw).List()
	return r, counter, err
}

func (this *Config) Add() (interface{}, error) {
	
	return this.Param().SetSend(this).Insert()
}

func (this *Config) Edit(mw func(db.Result) db.Result) error {
	this.Updated = uint(time.Now().Unix())
	return this.Param().SetSend(this).SetMiddleware(mw).Update()
}

func (this *Config) Delete(mw func(db.Result) db.Result) error {
	
	return this.Param().SetMiddleware(mw).Delete()
}

